### ISSUE TITLE
Numpy package conflict for gammapy v0.14

### ISSUE THREAD

**Issue by cdeil** [conda-forge/gammapy-feedstock#12]
With a clean system:
```
docker pull continuumio/miniconda
docker run -i -t continuumio/miniconda /bin/bash
```
I get this error trying to install the Gammapy v0.14 released earlier today (see #11 and https://docs.gammapy.org/0.14/install/index.html):
```
$ wget https://gammapy.org/download/install/gammapy-0.14-environment.yml
(base) root@8bc7ff141cb8:/# conda env create -f gammapy-0.14-environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package numpy conflicts for:
uncertainties=3.1 -> numpy
numpy=1.16
naima=0.8.3 -> corner -> matplotlib -> numpy
corner=2.0 -> matplotlib -> numpy
astropy=3.2 -> numpy[version='1.13.*,>=1.11.3,<2.0a0,>=1.14']
gammapy=0.14 -> scipy[version='>=1.2'] -> numpy[version='>=1.11.3,<2.0a0,>=1.9.3,<2.0a0']
matplotlib=3.0 -> numpy
sherpa=4.11 -> numpy[version='>1.11']
regions=0.4 -> numpy[version='>=1.14.6,<2.0a0']
scipy=1.2 -> numpy[version='1.10.*,>=1.11.3,<2.0a0,>=1.9.3,<2.0a0']
reproject=0.5 -> scipy[version='>=0.9'] -> numpy[version='>=1.11.3,<2.0a0,>=1.9.3,<2.0a0']
iminuit=1.3.7 -> numpy[version='>=1.11.3,<2.0a0,>=1.14.6,<2.0a0']
emcee=2.2 -> numpy
pandas=0.25 -> numpy[version='>=1.13.3,<2.0a0,>=1.14.6,<2.0a0']
healpy=1.12 -> scipy -> numpy[version='1.10.*,>=1.11.3,<2.0a0,>=1.9.3,<2.0a0']
```

@bsipocz @astrofrog-conda-forge @bultako @adonath or anyone - do you know what's wrong? I don't understand why `numpy=1.16` causes a a package conflict?

Did we make a mistake in packaging v0.14, or in Numpy dependency specification in meta.yml?
(I tried to update meta.yml to follow the guide) Should we change to numpy 1.17?

**Comment by cdeil** [comment]
On macOS conda tries for ~ 30 minutes and then also produces an UnsatisfiableError for numpy (https://gist.github.com/cdeil/49b423689776d2bf640be7527bab1370#file-gistfile1-txt-L34) and there I see
```
gammapy=0.14 -> numpy[version='>=1.17.2,<2.0a0']
```
Where does this >= 1.17.2 come from?

**Comment by cdeil** [comment]
I think bumping the env to numpy=1.17 works for now:
https://github.com/gammapy/gammapy-webpage/commit/83bfd8771336bebfb193416ce965b6f479c80a0c

Still, maybe we should change one of these two lines (or something else) to build against an older Numpy? (is it currently 1.16 or 1.17?)

https://github.com/conda-forge/gammapy-feedstock/blob/25d523ccdadee5dd80b12d3518de5d18a3186ae8/recipe/meta.yaml#L29

https://github.com/conda-forge/gammapy-feedstock/blob/25d523ccdadee5dd80b12d3518de5d18a3186ae8/recipe/meta.yaml#L33

**Comment by bsipocz** [comment]
and where does the `<2.0a0` part coming from? numpy 2.0 doesn't seem to be a thing yet?

**Comment by cdeil** [comment]
I don't know. It looks like several packages have that. Probably a good setting for binary packages, if the expectation is that Numpy will only bump to v2.0 if they break v1.x compatibility.

**Comment by bsipocz** [comment]
I would keep the `numpy >=1.16` part for now as it uses less machinery to figure out the compatibilities.
